### ISSUE TITLE
contour with (x,y) being ranges

### ISSUE THREAD

**Issue by PaulSoderlind** [stevengj/PythonPlot.jl#8] opened 2022-04-15 12:52 UTC
crashes. (In contrast, several other plot types work with ranges, for instance, surf and plot.)

Example: 
```
x = -10:10
y = range(-5,5,length=11)
z = x.^2 .+ y'.^2

figure()
  contour(x, y, z')                            #crashes
  #contour(collect(x), collect(y), z')         #works
```

**Comment by stevengj** [comment] 2022-04-15 20:38
It throws an exception, which is not the same as "crashing".

**Comment by stevengj** [comment] 2022-04-15 20:43
The problem seems to be `y`.  If you replace `y` with `collect(y)` it works.  PythonCall translates these as:
```
julia> Py(y)
Python VectorValue: <jl -5.0:1.0:5.0>

julia> Py(collect(y))
Python VectorValue: <jl [-5.0, -4.0, -3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0]>
```
so Matplotlib doesn't mind a PythonCall `VectorValue` built from a `Vector`, but it doesn't like a `VectorValue` built from a `StepRangeLen` for some reason.  Maybe there is some missing method that PythonCall should have implemented in the latter case?

**Comment by stevengj** [comment] 2022-04-15 20:45
In particular, the problem seems to be that `np.asarray` doesn't like `StepRangeLen`:
```jl
julia> np = pyimport("numpy")
Python module: <module 'numpy' from '/Users/stevenj/.julia/environments/v1.7/.CondaPkg/env/lib/python3.10/site-packages/numpy/__init__.py'>

julia> np.asarray(y, dtype=np.float64)
ERROR: Python: TypeError: ArrayValue.__array__() takes 1 positional argument but 2 were given
Python stacktrace: none
Stacktrace:
 [1] pythrow()
   @ PythonCall ~/.julia/packages/PythonCall/XgP8G/src/err.jl:94
 [2] errcheck
   @ ~/.julia/packages/PythonCall/XgP8G/src/err.jl:10 [inlined]
 [3] pycallargs
   @ ~/.julia/packages/PythonCall/XgP8G/src/abstract/object.jl:154 [inlined]
 [4] pycall(f::Py, args::StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}; kwargs::Base.Pairs{Symbol, Py, Tuple{Symbol}, NamedTuple{(:dtype,), Tuple{Py}}})
   @ PythonCall ~/.julia/packages/PythonCall/XgP8G/src/abstract/object.jl:165
 [5] #_#11
   @ ~/.julia/packages/PythonCall/XgP8G/src/Py.jl:360 [inlined]
 [6] top-level scope
   @ REPL[15]:1

julia> np.asarray(collect(y), dtype=np.float64)
Python ndarray: array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.])
```

**Comment by stevengj** [comment] 2022-04-15 20:49
This works fine:
```jl
julia> np.asarray(y)
Python ndarray: array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.])
```
So the problem is the `dtype` argument.

**Comment by stevengj** [comment] 2022-04-15 20:51
It looks like the problem is that [this `__array__` method in PythonCall](https://github.com/cjdoris/PythonCall.jl/blob/b4528b71e9878c8a71b9bd48ff759b5d5b14267f/src/jlwrap/array.jl#L317-L326) doesn't accept the optional `dtype` argument.

**Comment by stevengj** [comment] 2022-04-21 13:19
Closed by https://github.com/cjdoris/PythonCall.jl/commit/be521aa7349875a407d350c7553f185752e54e3b

**Closed as completed by stevengj** 2022-04-21 13:19 UTC
Labels: pythoncall
